
name: bip-bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python bot.py

      - name: Commit seen file
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "bip-bot"
            git config user.email "bip-bot@users.noreply.github.com"
            git add seen_thoughts.txt
            git commit -m "update seen"
            git push
          fi
